#!/usr/bin/env python3

import shubhlipi as sh
import typer

app = typer.Typer()


@app.command("build-deps")
def build_dependecies():
    """Build Dependencies"""
    sh.cmd("pipenv requirements --exclude-markers > requirements.txt", display=False)
    fl = sh.read("./requirements.txt")
    fl = fl.replace("-i https://pypi.org/simple\n", "")
    sh.write("./src/requirements.txt", fl)
    sh.delete_file("./requirements.txt")


@app.command("format")
def code_format_command():
    """Format the code using black"""
    sh.cmd("black .", display=False)


if __name__ == "__main__":
    app()
