name: deploy to deta space

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_deploy:
    name: Build Dependencies and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.9
      - name: Generate requirements.txt
        run : |
          pip install pipenv typer shubhlipi
          ./kry build-deps
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Deploy
        uses: lizheming/deta-action@master
        with:
          access_token: Q7maEmvQ_gQ7p9j7iat8yWqD9iVJVQyVabGQsa4as
          id: d0zhiKbTg5kM