name: deploy to deta space

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: build dependencies
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.9
      - name: generate requirements.txt
        run: |
          pip install pipenv typer shubhlipi
          ./kry build-deps
      - name: Deta Space Deployment Github Action
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          project_id: ${{ vars.SPACE_ID }}
          # define the above as repository 'secrests' and 'vars'
          space_push: true
          space_release: false
          list_on_discovery: false